### PR TITLE
create top level BsPostgres module

### PR DESCRIPTION
**Pull request by adnelson**
The module names `Client`, `Pool`, etc are very generic. This makes it more likely to clash with existing module names in code bases which want to use the library, as well as making it less clear in the code what library the modules are coming from. This change will prefix these modules with `BsPostgres_` and provide a single `BsPostgres` module which exposes all of them (same convention as in e.g. `Belt`)

### CODE REVIEW

**Comment by Risto-Stevcev** [comment]
Thanks for the PR. It's already namespaced though via `bsconfig.json`->`namespace: true`. That makes sure that code using this library has to call it with the module name like this:

```ocaml
let pool = fun () -> BsPostgres.Pool.make ~host:"localhost" ~user:"postgres" ~database:"postgres" ~port:5432 ()
```

**Comment by adnelson** [comment]
Oh, is that so? OK, I had no idea 😅 well thanks for taking the time to comment! I can close this then :)

**Comment by Risto-Stevcev** [comment]
Np :slightly_smiling_face: , yeah it's not obvious that you can do that it's kind of buried in the documentation. They should probably create a separate main section in the docs talking about library dev

**Comment by adnelson** [comment]
Agreed, but also it's just a part of the learning process. If I may, I think it would be helpful to provide a code example in the readme to clear this up, since the code in the tests doesn't use the top-level module. Also, because having copy/pastable code snippets in a readme is helpful in general :)

**Comment by Risto-Stevcev** [comment]
That's true, yeah go for it :slightly_smiling_face:

**Pull request closed without merging**
